--------------------------------------------------------
--  Ref Constraints for Table PLANTCONSTRAINTS
--------------------------------------------------------

  ALTER TABLE "JAREDBACH"."PLANTCONSTRAINTS" ADD FOREIGN KEY ("PLANTPRODCUST_ID")
	  REFERENCES "JAREDBACH"."PLANTPRODCUST" ("PLANTPRODCUST_ID") ENABLE;
  ALTER TABLE "JAREDBACH"."PLANTCONSTRAINTS" ADD FOREIGN KEY ("PORT_LOCATION_ID")
	  REFERENCES "JAREDBACH"."ORIG_PORT_LOCATIONS" ("ORIG_PORT_LOCATION_ID") ENABLE;
