--------------------------------------------------------
--  DDL for Table PLANTCONSTRAINTS
--------------------------------------------------------

  CREATE TABLE "JAREDBACH"."PLANTCONSTRAINTS" 
   (	"PLANTCODE_CONSTRAINT_ID" NUMBER(38,0), 
	"PLANTPRODCUST_ID" NUMBER(38,0), 
	"PORT_LOCATION_ID" NUMBER(38,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
