--------------------------------------------------------
--  Ref Constraints for Table PORTCARRIER
--------------------------------------------------------

  ALTER TABLE "JAREDBACH"."PORTCARRIER" ADD FOREIGN KEY ("ORIG_PORT_LOCATION_ID")
	  REFERENCES "JAREDBACH"."ORIG_PORT_LOCATIONS" ("ORIG_PORT_LOCATION_ID") ENABLE;
  ALTER TABLE "JAREDBACH"."PORTCARRIER" ADD FOREIGN KEY ("DEST_PORT_LOCATION_ID")
	  REFERENCES "JAREDBACH"."DEST_PORT_LOCATIONS" ("DEST_PORT_LOCATION_ID") ENABLE;
