--------------------------------------------------------
--  File created - Wednesday-November-03-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PORT_LOCATIONS
--------------------------------------------------------

  CREATE TABLE "JAREDBACH"."PORT_LOCATIONS" 
   (	"PORT_LOCATION_ID" NUMBER(38,0), 
	"PORTS" VARCHAR2(26 BYTE), 
	"PORT_CITY" VARCHAR2(26 BYTE), 
	"PORT_STATE_NAME" VARCHAR2(26 BYTE), 
	"PORT_STATE" VARCHAR2(26 BYTE), 
	"PORT_LONGITUDE" NUMBER(38,8), 
	"PORT_LATITUDE" NUMBER(38,8)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into JAREDBACH.PORT_LOCATIONS
SET DEFINE OFF;
Insert into JAREDBACH.PORT_LOCATIONS (PORT_LOCATION_ID,PORTS,PORT_CITY,PORT_STATE_NAME,PORT_STATE,PORT_LONGITUDE,PORT_LATITUDE) values (1,'PORT01','Camden','New Jersey','NJ',-75.12338257,39.93738174);
Insert into JAREDBACH.PORT_LOCATIONS (PORT_LOCATION_ID,PORTS,PORT_CITY,PORT_STATE_NAME,PORT_STATE,PORT_LONGITUDE,PORT_LATITUDE) values (2,'PORT02','Philadelphia','Pennsylvania','PA',-75.09488,39.979031);
Insert into JAREDBACH.PORT_LOCATIONS (PORT_LOCATION_ID,PORTS,PORT_CITY,PORT_STATE_NAME,PORT_STATE,PORT_LONGITUDE,PORT_LATITUDE) values (3,'PORT03','Boston','Massachusetts','MA',-71.0389415,42.3481664);
Insert into JAREDBACH.PORT_LOCATIONS (PORT_LOCATION_ID,PORTS,PORT_CITY,PORT_STATE_NAME,PORT_STATE,PORT_LONGITUDE,PORT_LATITUDE) values (4,'PORT04','Miami','Florida','FL',-80.1779964,25.778567);
Insert into JAREDBACH.PORT_LOCATIONS (PORT_LOCATION_ID,PORTS,PORT_CITY,PORT_STATE_NAME,PORT_STATE,PORT_LONGITUDE,PORT_LATITUDE) values (5,'PORT05','Wilmington','North Carolina','NC',-77.9479854,34.196556);
Insert into JAREDBACH.PORT_LOCATIONS (PORT_LOCATION_ID,PORTS,PORT_CITY,PORT_STATE_NAME,PORT_STATE,PORT_LONGITUDE,PORT_LATITUDE) values (6,'PORT06','Baltimore','Maryland','MD',-76.6096734,39.2860811);
Insert into JAREDBACH.PORT_LOCATIONS (PORT_LOCATION_ID,PORTS,PORT_CITY,PORT_STATE_NAME,PORT_STATE,PORT_LONGITUDE,PORT_LATITUDE) values (7,'PORT07','Bayonne','New Jersey','NJ',-74.547283,40.287226);
Insert into JAREDBACH.PORT_LOCATIONS (PORT_LOCATION_ID,PORTS,PORT_CITY,PORT_STATE_NAME,PORT_STATE,PORT_LONGITUDE,PORT_LATITUDE) values (8,'PORT08','Charleston','South Carolina','SC',-79.9257181,32.7808424);
Insert into JAREDBACH.PORT_LOCATIONS (PORT_LOCATION_ID,PORTS,PORT_CITY,PORT_STATE_NAME,PORT_STATE,PORT_LONGITUDE,PORT_LATITUDE) values (9,'PORT09','San Pedro','California','CA',-118.2813644,33.73823547);
Insert into JAREDBACH.PORT_LOCATIONS (PORT_LOCATION_ID,PORTS,PORT_CITY,PORT_STATE_NAME,PORT_STATE,PORT_LONGITUDE,PORT_LATITUDE) values (10,'PORT10','Savannah','Georgia','GA',-81.150809,32.123742);
Insert into JAREDBACH.PORT_LOCATIONS (PORT_LOCATION_ID,PORTS,PORT_CITY,PORT_STATE_NAME,PORT_STATE,PORT_LONGITUDE,PORT_LATITUDE) values (11,'PORT11','New York','New York','NY',-74.0056639,40.6830965);