--------------------------------------------------------
--  File created - Wednesday-November-03-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PORTCARRIER
--------------------------------------------------------

  CREATE TABLE "JAREDBACH"."PORTCARRIER" 
   (	"PORTCARRIER_ID" NUMBER(38,0), 
	"CARRIER" VARCHAR2(26 BYTE), 
	"SERVICE_LEVEL" VARCHAR2(26 BYTE), 
	"ORIG_PORT_LOCATION_ID" NUMBER(38,0), 
	"DEST_PORT_LOCATION_ID" NUMBER(38,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into JAREDBACH.PORTCARRIER
SET DEFINE OFF;
Insert into JAREDBACH.PORTCARRIER (PORTCARRIER_ID,CARRIER,SERVICE_LEVEL,ORIG_PORT_LOCATION_ID,DEST_PORT_LOCATION_ID) values (7410,'V44_3','CRF',9,9);
Insert into JAREDBACH.PORTCARRIER (PORTCARRIER_ID,CARRIER,SERVICE_LEVEL,ORIG_PORT_LOCATION_ID,DEST_PORT_LOCATION_ID) values (7411,'V44_3','CRF',5,9);
Insert into JAREDBACH.PORTCARRIER (PORTCARRIER_ID,CARRIER,SERVICE_LEVEL,ORIG_PORT_LOCATION_ID,DEST_PORT_LOCATION_ID) values (7412,'V44_3','CRF',4,9);
Insert into JAREDBACH.PORTCARRIER (PORTCARRIER_ID,CARRIER,SERVICE_LEVEL,ORIG_PORT_LOCATION_ID,DEST_PORT_LOCATION_ID) values (7413,'V444_0','DTP',4,9);
Insert into JAREDBACH.PORTCARRIER (PORTCARRIER_ID,CARRIER,SERVICE_LEVEL,ORIG_PORT_LOCATION_ID,DEST_PORT_LOCATION_ID) values (7414,'V444_6','DTD',8,9);
Insert into JAREDBACH.PORTCARRIER (PORTCARRIER_ID,CARRIER,SERVICE_LEVEL,ORIG_PORT_LOCATION_ID,DEST_PORT_LOCATION_ID) values (7415,'V444_6','DTD',10,9);
Insert into JAREDBACH.PORTCARRIER (PORTCARRIER_ID,CARRIER,SERVICE_LEVEL,ORIG_PORT_LOCATION_ID,DEST_PORT_LOCATION_ID) values (7416,'V444_9','DTD',8,9);
Insert into JAREDBACH.PORTCARRIER (PORTCARRIER_ID,CARRIER,SERVICE_LEVEL,ORIG_PORT_LOCATION_ID,DEST_PORT_LOCATION_ID) values (7417,'V444_2','DTD',11,9);
Insert into JAREDBACH.PORTCARRIER (PORTCARRIER_ID,CARRIER,SERVICE_LEVEL,ORIG_PORT_LOCATION_ID,DEST_PORT_LOCATION_ID) values (7418,'V444_2','DTP',11,9);
Insert into JAREDBACH.PORTCARRIER (PORTCARRIER_ID,CARRIER,SERVICE_LEVEL,ORIG_PORT_LOCATION_ID,DEST_PORT_LOCATION_ID) values (7419,'V444_2','DTP',7,9);
Insert into JAREDBACH.PORTCARRIER (PORTCARRIER_ID,CARRIER,SERVICE_LEVEL,ORIG_PORT_LOCATION_ID,DEST_PORT_LOCATION_ID) values (7420,'V444_2','DTD',8,9);
Insert into JAREDBACH.PORTCARRIER (PORTCARRIER_ID,CARRIER,SERVICE_LEVEL,ORIG_PORT_LOCATION_ID,DEST_PORT_LOCATION_ID) values (7421,'V444_2','DTP',8,9);
Insert into JAREDBACH.PORTCARRIER (PORTCARRIER_ID,CARRIER,SERVICE_LEVEL,ORIG_PORT_LOCATION_ID,DEST_PORT_LOCATION_ID) values (7422,'V444_0','DTD',2,9);
Insert into JAREDBACH.PORTCARRIER (PORTCARRIER_ID,CARRIER,SERVICE_LEVEL,ORIG_PORT_LOCATION_ID,DEST_PORT_LOCATION_ID) values (7423,'V444_2','DTD',7,9);
Insert into JAREDBACH.PORTCARRIER (PORTCARRIER_ID,CARRIER,SERVICE_LEVEL,ORIG_PORT_LOCATION_ID,DEST_PORT_LOCATION_ID) values (7424,'V444_2','DTD',2,9);
Insert into JAREDBACH.PORTCARRIER (PORTCARRIER_ID,CARRIER,SERVICE_LEVEL,ORIG_PORT_LOCATION_ID,DEST_PORT_LOCATION_ID) values (7425,'V444_1','DTD',6,9);
Insert into JAREDBACH.PORTCARRIER (PORTCARRIER_ID,CARRIER,SERVICE_LEVEL,ORIG_PORT_LOCATION_ID,DEST_PORT_LOCATION_ID) values (7426,'V444_2','DTD',10,9);
Insert into JAREDBACH.PORTCARRIER (PORTCARRIER_ID,CARRIER,SERVICE_LEVEL,ORIG_PORT_LOCATION_ID,DEST_PORT_LOCATION_ID) values (7427,'V444_2','DTP',10,9);
Insert into JAREDBACH.PORTCARRIER (PORTCARRIER_ID,CARRIER,SERVICE_LEVEL,ORIG_PORT_LOCATION_ID,DEST_PORT_LOCATION_ID) values (7428,'V444_1','DTD',10,9);
Insert into JAREDBACH.PORTCARRIER (PORTCARRIER_ID,CARRIER,SERVICE_LEVEL,ORIG_PORT_LOCATION_ID,DEST_PORT_LOCATION_ID) values (7429,'V444_4','DTD',10,9);
Insert into JAREDBACH.PORTCARRIER (PORTCARRIER_ID,CARRIER,SERVICE_LEVEL,ORIG_PORT_LOCATION_ID,DEST_PORT_LOCATION_ID) values (7430,'V444_4','DTD',6,9);
Insert into JAREDBACH.PORTCARRIER (PORTCARRIER_ID,CARRIER,SERVICE_LEVEL,ORIG_PORT_LOCATION_ID,DEST_PORT_LOCATION_ID) values (7431,'V444_4','DTP',6,9);
Insert into JAREDBACH.PORTCARRIER (PORTCARRIER_ID,CARRIER,SERVICE_LEVEL,ORIG_PORT_LOCATION_ID,DEST_PORT_LOCATION_ID) values (7432,'V444_8','DTD',9,9);
Insert into JAREDBACH.PORTCARRIER (PORTCARRIER_ID,CARRIER,SERVICE_LEVEL,ORIG_PORT_LOCATION_ID,DEST_PORT_LOCATION_ID) values (7433,'V444_8','DTD',11,9);
Insert into JAREDBACH.PORTCARRIER (PORTCARRIER_ID,CARRIER,SERVICE_LEVEL,ORIG_PORT_LOCATION_ID,DEST_PORT_LOCATION_ID) values (7434,'V444_0','DTD',4,9);
Insert into JAREDBACH.PORTCARRIER (PORTCARRIER_ID,CARRIER,SERVICE_LEVEL,ORIG_PORT_LOCATION_ID,DEST_PORT_LOCATION_ID) values (7435,'V444_8','DTD',4,9);
Insert into JAREDBACH.PORTCARRIER (PORTCARRIER_ID,CARRIER,SERVICE_LEVEL,ORIG_PORT_LOCATION_ID,DEST_PORT_LOCATION_ID) values (7436,'V444_8','DTD',2,9);
Insert into JAREDBACH.PORTCARRIER (PORTCARRIER_ID,CARRIER,SERVICE_LEVEL,ORIG_PORT_LOCATION_ID,DEST_PORT_LOCATION_ID) values (7437,'V444_5','DTD',2,9);
Insert into JAREDBACH.PORTCARRIER (PORTCARRIER_ID,CARRIER,SERVICE_LEVEL,ORIG_PORT_LOCATION_ID,DEST_PORT_LOCATION_ID) values (7438,'V444_5','DTP',2,9);
Insert into JAREDBACH.PORTCARRIER (PORTCARRIER_ID,CARRIER,SERVICE_LEVEL,ORIG_PORT_LOCATION_ID,DEST_PORT_LOCATION_ID) values (7439,'V444_5','DTD',5,9);
Insert into JAREDBACH.PORTCARRIER (PORTCARRIER_ID,CARRIER,SERVICE_LEVEL,ORIG_PORT_LOCATION_ID,DEST_PORT_LOCATION_ID) values (7440,'V444_5','DTP',5,9);
Insert into JAREDBACH.PORTCARRIER (PORTCARRIER_ID,CARRIER,SERVICE_LEVEL,ORIG_PORT_LOCATION_ID,DEST_PORT_LOCATION_ID) values (7441,'V444_1','DTD',5,9);
Insert into JAREDBACH.PORTCARRIER (PORTCARRIER_ID,CARRIER,SERVICE_LEVEL,ORIG_PORT_LOCATION_ID,DEST_PORT_LOCATION_ID) values (7442,'V444_7','DTD',3,9);
Insert into JAREDBACH.PORTCARRIER (PORTCARRIER_ID,CARRIER,SERVICE_LEVEL,ORIG_PORT_LOCATION_ID,DEST_PORT_LOCATION_ID) values (7443,'V444_8','DTD',3,9);
Insert into JAREDBACH.PORTCARRIER (PORTCARRIER_ID,CARRIER,SERVICE_LEVEL,ORIG_PORT_LOCATION_ID,DEST_PORT_LOCATION_ID) values (7444,'V444_5','DTD',6,9);
Insert into JAREDBACH.PORTCARRIER (PORTCARRIER_ID,CARRIER,SERVICE_LEVEL,ORIG_PORT_LOCATION_ID,DEST_PORT_LOCATION_ID) values (7445,'V444_5','DTP',6,9);
Insert into JAREDBACH.PORTCARRIER (PORTCARRIER_ID,CARRIER,SERVICE_LEVEL,ORIG_PORT_LOCATION_ID,DEST_PORT_LOCATION_ID) values (7446,'V444_5','DTD',9,9);
Insert into JAREDBACH.PORTCARRIER (PORTCARRIER_ID,CARRIER,SERVICE_LEVEL,ORIG_PORT_LOCATION_ID,DEST_PORT_LOCATION_ID) values (7447,'V444_4','DTD',4,9);
Insert into JAREDBACH.PORTCARRIER (PORTCARRIER_ID,CARRIER,SERVICE_LEVEL,ORIG_PORT_LOCATION_ID,DEST_PORT_LOCATION_ID) values (7448,'V444_1','DTD',4,9);
Insert into JAREDBACH.PORTCARRIER (PORTCARRIER_ID,CARRIER,SERVICE_LEVEL,ORIG_PORT_LOCATION_ID,DEST_PORT_LOCATION_ID) values (7449,'V444_5','DTD',3,9);
Insert into JAREDBACH.PORTCARRIER (PORTCARRIER_ID,CARRIER,SERVICE_LEVEL,ORIG_PORT_LOCATION_ID,DEST_PORT_LOCATION_ID) values (7450,'V444_0','DTD',3,9);
Insert into JAREDBACH.PORTCARRIER (PORTCARRIER_ID,CARRIER,SERVICE_LEVEL,ORIG_PORT_LOCATION_ID,DEST_PORT_LOCATION_ID) values (7451,'V444_5','DTP',9,9);
Insert into JAREDBACH.PORTCARRIER (PORTCARRIER_ID,CARRIER,SERVICE_LEVEL,ORIG_PORT_LOCATION_ID,DEST_PORT_LOCATION_ID) values (7452,'V444_0','DTP',9,9);
Insert into JAREDBACH.PORTCARRIER (PORTCARRIER_ID,CARRIER,SERVICE_LEVEL,ORIG_PORT_LOCATION_ID,DEST_PORT_LOCATION_ID) values (7453,'V444_0','DTD',9,9);
Insert into JAREDBACH.PORTCARRIER (PORTCARRIER_ID,CARRIER,SERVICE_LEVEL,ORIG_PORT_LOCATION_ID,DEST_PORT_LOCATION_ID) values (7454,'V444_4','DTD',5,9);
Insert into JAREDBACH.PORTCARRIER (PORTCARRIER_ID,CARRIER,SERVICE_LEVEL,ORIG_PORT_LOCATION_ID,DEST_PORT_LOCATION_ID) values (7455,'V444_1','DTD',2,9);
Insert into JAREDBACH.PORTCARRIER (PORTCARRIER_ID,CARRIER,SERVICE_LEVEL,ORIG_PORT_LOCATION_ID,DEST_PORT_LOCATION_ID) values (7456,'V444_4','DTD',2,9);

