--------------------------------------------------------
--  DDL for Table FACTTABLE
--------------------------------------------------------

  CREATE TABLE "JAREDBACH"."FACTTABLE" 
   (	"PLANTCODE_CONSTRAINT_ID" NUMBER(38,0), 
	"ORDER_ID" NUMBER(38,0), 
	"FREIGHT_RATES_ID" NUMBER(38,0), 
	"PORTCARRIER_ID" NUMBER(38,0), 
	"PLANTPRODCUST_ID" NUMBER(38,0), 
	"MIN_WEIGHT_QUANT" NUMBER(38,0), 
	"MAX_WEIGHT_QUANT" NUMBER(38,0), 
	"MIN_COST" NUMBER(38,0), 
	"RATE" NUMBER(38,0), 
	"TPT_DAY_COUNT" NUMBER(38,0), 
	"COST_PER_UNIT" NUMBER(38,0), 
	"DAILY_CAPACITY" NUMBER(38,0), 
	"SHIP_AHEAD_DAY_COUNT" NUMBER(38,0), 
	"SHIP_LATE_DAY_COUNT" NUMBER(38,0), 
	"UNIT_QUANT" NUMBER(38,0), 
	"WEIGHT" NUMBER(38,0), 
	"LOCATION_ID" NUMBER(38,0), 
	"DEST_PORT_LOCATION_ID" NUMBER(38,0), 
	"ORIG_PORT_LOCATION_ID" NUMBER(38,0), 
	"PLANT_LOCATION_ID" NUMBER(38,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
