--------------------------------------------------------
--  DDL for Table DEST_PORT_LOCATIONS
--------------------------------------------------------

  CREATE TABLE "JAREDBACH"."DEST_PORT_LOCATIONS" 
   (	"DEST_PORT_LOCATION_ID" NUMBER(38,0), 
	"LOCATION_ID" NUMBER(38,0), 
	"DEST_PORT" VARCHAR2(26 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
