--------------------------------------------------------
--  DDL for Table LOCATIONS
--------------------------------------------------------

  CREATE TABLE "JAREDBACH"."LOCATIONS" 
   (	"LOCATION_ID" NUMBER(38,0), 
	"CITY" VARCHAR2(26 BYTE), 
	"STATE_NAME" VARCHAR2(26 BYTE), 
	"STATE" VARCHAR2(26 BYTE), 
	"LONGITUDE" NUMBER(38,8), 
	"LATITUDE" NUMBER(38,8)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
