--------------------------------------------------------
--  DDL for Table FREIGHTRATES
--------------------------------------------------------

  CREATE TABLE "JAREDBACH"."FREIGHTRATES" 
   (	"MODE_DSC" VARCHAR2(26 BYTE), 
	"CARRIER_TYPE" VARCHAR2(26 BYTE), 
	"FREIGHT_RATES_ID" NUMBER(38,0), 
	"PORTCARRIER_ID" NUMBER(38,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
